# Converts Jupyter Notebooks v4 into Python scripts.
import sys
import json
import os

def export(filename):
  '''Converts notebook into python script.'''
  with open(filename, 'r') as f:
    nb = json.load(f)

  main_func, code, top = [], [], []
  for cell in nb["cells"]:
    if cell['cell_type'] != 'code' or not cell['source']:
      continue

    first_line, *source = cell['source']
    if first_line.startswith('# export'):
      code += ['# cell\n', *source, '\n\n']
    elif first_line.startswith('# main'):
      main_func += ['# cell\n', *source, '\n\n']
    elif first_line.startswith('# top'):
      top += [*source, '\n']

  with open(f'{filename[:-6]}.py', 'w') as f:
    if top:
      f.write(f'# Autogenerated from {filename}.\n')
      f.write(''.join(top))
      f.write('\n\n')
    else:
      f.write(f'# Autogenerated from {filename}.\n\n')

    f.write(''.join(code))
    if main_func:
      f.write('\n\ndef main():\n')
      f.write('  ' + '  '.join(main_func))
      f.write("\nif __name__ == '__main__':\n  main()")
        
def export_all():
  '''Converts all notebooks in current directory to python scripts.'''
  for filename in os.listdir():
    if filename.endswith('.ipynb'):
      export(filename)

if __name__ == '__main__':
  export_all()  

